### ISSUE TITLE
No Graphics on Pi4 ?

### ISSUE THREAD

**Issue by soaresden** [pajarorrojo/es-theme-PlayStation-X#1]
Hi ! 

I was very excited for your theme ! Used the theme downloader built-in But when applied, Nothing changed :(

* I can only seen a bit of theme by pressing start for the menu. then the background is loaded, font etc...
* there is no "extra" customisation menu on theme ?
* After a reboot, only the loading screen was OK. The black menu and gamelists are black :/

I don't know why it doesn't work ? Maybe a path issue ? I don't know..

If you want more infos, please feel free to ask me

Pi4 on v31-dev 2021/03/24 17:56

Edit : Fixed by downloading myself on PC and replacing files manually 
Seems that Batocera downloadr corrupt the files ? I don't know. .

**Comment by pajarorrojo** [comment]
Thank you very much for alert me, it is already fixed. Can you delete the corrupted theme and download it again, please? You will find many options in the theme, I hope you like it and that you enjoy it.

**Comment by soaresden** [comment]
Yes :) Really Good 

I prefer my font but I was able to replace it manuall ;)
[Vag Rounded Gras.zip](https://github.com/pajarorrojo/es-theme-PlayStation-X/files/6207459/Vag.Rounded.Gras.zip)

I'm closing the issue

**Comment by pajarorrojo** [comment]
Great, good typo!, but being true to the original, I prefer the "official" from sony ;)

https://www.sony.net/SonyInfo/design/stories/sst-font/

**Comment by soaresden** [comment]
Sure it's faithful theme, 
Great Job

Juste a last questio, the numbers 17, 262 on the top, ... I don't know the significations about it ? 
Are they random ?

**Comment by pajarorrojo** [comment]
Are just numbers for design purpose.... in the last version i change the 17 for a 31 for the current batocera beta version, but are just numbers not feeding by nothing in concrete
