### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Ogami-FR** [pajarorrojo/es-theme-PlayStation-X#3]
Hello,
I cannot download your theme from the github site (corrupted zip) or from ubuntu (git clone = incomplete).
Could you provide us with a pre-zip release version, please.

thank you in advance

**Comment by pajarorrojo** [comment]
Hello Ogami. 
I don't see any problem in the downloaded zip or in the repository, it was probably a specific network problem, I don't know. Can you try again please?

**Comment by Ogami-FR** [comment]
I was able to download it with ubuntu "git clone".
But impossible to download it normally from github.com.
Great theme! I really like :) 
keep up the great work !

**Comment by pajarorrojo** [comment]
Perfect! hope you enjoy and thanks so much for your words!
