### ISSUE TITLE
Not able to change avatar or username at all.

### ISSUE THREAD

**Issue by T-622** [pajarorrojo/es-theme-PlayStation-X#7]
Hello, I was hopin gyou could point me in the right direction with this. I have changed the custom username .XML file as well as changed the avatar .png. However, the theme always defaults to using the Batocera avatar and the Playstation-X username. How am I supossed to change this?

Thanks,
Tyler Peppy

**Comment by pajarorrojo** [comment]
Thanks, yes, I know, there is a problem in the code and in the next update it will be fixed. Anyway you have to select the customization in the theme options. "Choose a nick" or "choose your avatar" -> custom. But it won't work until the next update scheduled for a few days, stay tuned ;). Sorry for the inconvenience.

**Comment by T-622** [comment]
Sorry that I had bothered you; after 2 hours I actually stumbled across the options.

**Comment by pajarorrojo** [comment]
Don't worry, a pleasure to help. I don't know what version you use, but today I have updated to 32.2 with many new features and improvements. Enjoy it. Thanks
